version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - redis-1
  redis-slave1:
    container_name: redis-slave1
    image: redis:7.2
    depends_on: 
      - redis-master
    ports:
      - "6380:6379"
    networks:
      - redis-1
    command: ["redis-server", "--slaveof redis-master 6379"]
  redis-slave2:
    container_name: redis-slave2
    image: redis:7.2
    depends_on: 
      - redis-master
    ports:
      - "6381:6379"
    networks:
      - redis-1
    command: ["redis-server", "--slaveof redis-master 6379"]
  redis-slave3:
    container_name: redis-slave3
    image: redis:7.2
    depends_on: 
      - redis-master
    ports:
      - "6382:6379"
    networks:
      - redis-1
    command: ["redis-server", "--slaveof redis-master 6379"]
  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: redis:7.2
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    ports:
      - "6383:26379"
    networks:
      - redis-1
    volumes:
      - ./conf:/usr/local/etc/redis
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: redis:7.2
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    ports:
      - "6384:26379"
    networks:
      - redis-1
    volumes:
      - ./conf:/usr/local/etc/redis
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  redis-sentinel-3:
    container_name: redis-sentinel-3
    image: redis:7.2
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    ports:
      - "6385:26379"
    networks:
      - redis-1
    volumes:
      - ./conf:/usr/local/etc/redis
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
  spring-app:
    container_name: spring-app
    build: .
    image: spring-app
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      - redis-1
    ports:
      - "8085:8080"

networks:
  redis-1:
    driver: bridge